package main

import (
 "bytes"
 "crypto/ed25519"
 "crypto/sha256"
 "encoding/base64"
 "encoding/hex"
 "encoding/json"
 "encoding/xml"
 "errors"
 "fmt"
 "io"
 "net/http"
 "os"
 "os/exec"
 "path/filepath"
 "regexp"
 "slices"
 "strconv"
 "strings"

 "github.com/gin-gonic/gin"
)

const maxInput = 1 << 20
var codecRE = regexp.MustCompile(`^[a-z0-9_]+$`)

type rawProbe struct { Format struct { Name string `json:"format_name"`; Duration string `json:"duration"` } `json:"format"`; Streams []struct { Index json.Number `json:"index"`; Type string `json:"codec_type"`; Codec string `json:"codec_name"`; TimeBase string `json:"time_base"`; Width json.Number `json:"width"`; Height json.Number `json:"height"`; SampleRate string `json:"sample_rate"`; Channels json.Number `json:"channels"` } `json:"streams"` }
type stream struct { Index int64 `json:"index"`; Type string `json:"type"`; Codec string `json:"codec"`; TimeBase string `json:"time_base"`; Width int64 `json:"width,omitempty"`; Height int64 `json:"height,omitempty"`; SampleRate int64 `json:"sample_rate,omitempty"`; Channels int64 `json:"channels,omitempty"` }
type record struct { Media string `json:"media"`; Format string `json:"format"`; DurationUS int64 `json:"duration_us"`; Streams []stream `json:"streams"` }
type probeResponse struct { Record record `json:"record"`; Digest string `json:"digest"` }
type reportEdge struct { ID string `json:"id"`; Source string `json:"source"`; Target string `json:"target"`; Media string `json:"media"`; ProbeDigest string `json:"probe_digest"`; Signature string `json:"signature"` }
type report struct { Schema string `json:"schema"`; GraphID string `json:"graph_id"`; PublicKey string `json:"public_key"`; Edges []reportEdge `json:"edges"`; MerkleRoot string `json:"merkle_root"` }
type xKey struct { ID string `xml:"id,attr"`; For string `xml:"for,attr"`; Name string `xml:"attr.name,attr"` }
type xData struct { Key string `xml:"key,attr"`; Value string `xml:",chardata"` }
type xNode struct { ID string `xml:"id,attr"` }
type xEdge struct { ID string `xml:"id,attr"`; Source string `xml:"source,attr"`; Target string `xml:"target,attr"`; Data []xData `xml:"data"` }
type xGraph struct { ID string `xml:"id,attr"`; Default string `xml:"edgedefault,attr"`; Data []xData `xml:"data"`; Nodes []xNode `xml:"node"`; Edges []xEdge `xml:"edge"`; Graphs []xGraph `xml:"graph"` }
type xDoc struct { XMLName xml.Name `xml:"graphml"`; Keys []xKey `xml:"key"`; Graphs []xGraph `xml:"graph"` }

func posInt(s string, zero bool) (int64, error) { if s=="" || strings.ContainsAny(s,".+-eE ") { return 0,errors.New("invalid integer") }; n,e:=strconv.ParseInt(s,10,64); if e!=nil || n<0 || (!zero&&n==0) { return 0,errors.New("invalid integer") }; return n,nil }
func durationUS(s string)(int64,error){ if s==""||strings.ContainsAny(s,"+-eE "){return 0,errors.New("invalid duration")}; p:=strings.Split(s,"."); if len(p)>2||len(p[0])==0{return 0,errors.New("invalid duration")}; a,e:=posInt(p[0],true);if e!=nil{return 0,e}; frac:="";if len(p)==2{frac=p[1]};if len(frac)>6{return 0,errors.New("duration precision")};for _,c:=range frac{if c<'0'||c>'9'{return 0,errors.New("invalid duration")}};for len(frac)<6{frac+="0"};f:=int64(0);if frac!=""{f,_=strconv.ParseInt(frac,10,64)};if a>(1<<63-1-f)/1000000{return 0,errors.New("duration overflow")};n:=a*1000000+f;if n<=0{return 0,errors.New("nonpositive duration")};return n,nil }
func rational(s string)(string,error){p:=strings.Split(s,"/");if len(p)!=2{return "",errors.New("invalid time base")};n,e:=posInt(p[0],true);if e!=nil{return "",e};d,e:=posInt(p[1],false);if e!=nil{return "",e};g:=n;h:=d;for h!=0{g,h=h,g%h};if g==0{g=1};return fmt.Sprintf("%d/%d",n/g,d/g),nil}
func mediaPath(media string)(string,error){ if media==""||strings.HasPrefix(media,"/")||strings.Contains(media,"\\"){return "",errors.New("invalid media name")};for _,p:=range strings.Split(media,"/"){if p==""||p=="."||p==".."{return "",errors.New("invalid media name")}};root:=os.Getenv("MEDIA_ROOT");if root==""{root="/app/media"};rr,e:=filepath.EvalSymlinks(root);if e!=nil{return "",errors.New("media root unavailable")};candidate:=filepath.Join(rr,filepath.FromSlash(media));cur:=rr;for _,part:=range strings.Split(media,"/"){cur=filepath.Join(cur,part);fi,e:=os.Lstat(cur);if e!=nil||fi.Mode()&os.ModeSymlink!=0{return "",errors.New("invalid media file")}};real,e:=filepath.EvalSymlinks(candidate);if e!=nil{return "",errors.New("invalid media file")};rel,e:=filepath.Rel(rr,real);if e!=nil||rel==".."||strings.HasPrefix(rel,".."+string(os.PathSeparator)){return "",errors.New("media escapes root")};fi,e:=os.Stat(real);if e!=nil||!fi.Mode().IsRegular(){return "",errors.New("media is not regular")};return real,nil }
func probe(media string)(probeResponse,error){ var out probeResponse;path,e:=mediaPath(media);if e!=nil{return out,e};bin:=os.Getenv("FFPROBE_BIN");if bin==""{bin="ffprobe"};cmd:=exec.Command(bin,"-v","error","-show_entries","format=format_name,duration:stream=index,codec_type,codec_name,time_base,width,height,sample_rate,channels","-of","json",path);var buf bytes.Buffer;cmd.Stdout=&limitedWriter{w:&buf,n:maxInput};cmd.Stderr=io.Discard;if e=cmd.Run();e!=nil{return out,errors.New("ffprobe failed")};dec:=json.NewDecoder(bytes.NewReader(buf.Bytes()));dec.UseNumber();dec.DisallowUnknownFields();var raw rawProbe;if e=dec.Decode(&raw);e!=nil{return out,errors.New("invalid ffprobe output")};if dec.Decode(&struct{}{})!=io.EOF{return out,errors.New("trailing ffprobe output")};formats:=strings.Split(raw.Format.Name,",");seen:=map[string]bool{};clean:=[]string{};for _,f:=range formats{f=strings.TrimSpace(f);if f==""{return out,errors.New("invalid format")};if !seen[f]{seen[f]=true;clean=append(clean,f)}};slices.Sort(clean);dur,e:=durationUS(raw.Format.Duration);if e!=nil{return out,e};rec:=record{Media:media,Format:strings.Join(clean,","),DurationUS:dur,Streams:[]stream{}};idxSeen:=map[int64]bool{};videos:=0;for _,rs:=range raw.Streams{i,e:=posInt(rs.Index.String(),true);if e!=nil||idxSeen[i]{return out,errors.New("invalid stream index")};idxSeen[i]=true;if !codecRE.MatchString(rs.Codec){return out,errors.New("invalid codec")};tb,e:=rational(rs.TimeBase);if e!=nil{return out,e};s:=stream{Index:i,Type:rs.Type,Codec:rs.Codec,TimeBase:tb};switch rs.Type{case "video":videos++;s.Width,e=posInt(rs.Width.String(),false);if e==nil{s.Height,e=posInt(rs.Height.String(),false)};case "audio":s.SampleRate,e=posInt(rs.SampleRate,false);if e==nil{s.Channels,e=posInt(rs.Channels.String(),false)};default:return out,errors.New("unknown stream type")};if e!=nil{return out,e};rec.Streams=append(rec.Streams,s)};if videos!=1{return out,errors.New("requires one video stream")};slices.SortFunc(rec.Streams,func(a,b stream)int{return int(a.Index-b.Index)});b,_:=json.Marshal(rec);sum:=sha256.Sum256(b);return probeResponse{Record:rec,Digest:hex.EncodeToString(sum[:])},nil }
type limitedWriter struct{w io.Writer;n int};func(l *limitedWriter)Write(p []byte)(int,error){if len(p)>l.n{return 0,errors.New("ffprobe output too large")};n,e:=l.w.Write(p);l.n-=n;return n,e}
func dataMap(ds []xData,keys map[string]string,allowed map[string]bool)(map[string]string,error){m:=map[string]string{};for _,d:=range ds{name,ok:=keys[d.Key];if !ok||!allowed[name]{return nil,errors.New("unknown data")};if _,ok=m[name];ok{return nil,errors.New("duplicate data")};v:=strings.TrimSpace(d.Value);if v==""{return nil,errors.New("empty data")};m[name]=v};for k:=range allowed{if m[k]==""{return nil,errors.New("missing data")}};return m,nil}
func attest(path string)(report,error){var out report;fi,e:=os.Stat(path);if e!=nil||!fi.Mode().IsRegular()||fi.Size()>maxInput{return out,errors.New("invalid graph file")};f,e:=os.Open(path);if e!=nil{return out,e};defer f.Close();dec:=xml.NewDecoder(io.LimitReader(f,maxInput+1));var doc xDoc;if e=dec.Decode(&doc);e!=nil{return out,errors.New("invalid graphml")};if len(doc.Graphs)!=1{return out,errors.New("requires one graph")};keys:=map[string]string{};keyFor:=map[string]string{};for _,k:=range doc.Keys{if k.ID==""||keys[k.ID]!=""||(k.For!="graph"&&k.For!="edge"){return out,errors.New("invalid key")};keys[k.ID]=k.Name;keyFor[k.ID]=k.For};g:=doc.Graphs[0];if g.ID==""||g.Default!="directed"||len(g.Graphs)>0||len(g.Edges)==0{return out,errors.New("invalid graph")};for _,d:=range g.Data{if keyFor[d.Key]!="graph"{return out,errors.New("invalid graph data")}};gd,e:=dataMap(g.Data,keys,map[string]bool{"public_key":true});if e!=nil{return out,e};pub,e:=base64.StdEncoding.DecodeString(gd["public_key"]);if e!=nil||len(pub)!=ed25519.PublicKeySize{return out,errors.New("invalid public key")};nodes:=map[string]bool{};for _,n:=range g.Nodes{if n.ID==""||nodes[n.ID]{return out,errors.New("invalid node")};nodes[n.ID]=true};ids:=map[string]bool{};edges:=[]reportEdge{};for _,xe:=range g.Edges{if xe.ID==""||ids[xe.ID]||!nodes[xe.Source]||!nodes[xe.Target]{return out,errors.New("invalid edge")};ids[xe.ID]=true;for _,d:=range xe.Data{if keyFor[d.Key]!="edge"{return out,errors.New("invalid edge data")}};m,e:=dataMap(xe.Data,keys,map[string]bool{"media":true,"probe_digest":true,"signature":true});if e!=nil{return out,e};if len(m["probe_digest"])!=64||strings.ToLower(m["probe_digest"])!=m["probe_digest"]{return out,errors.New("invalid digest")};if _,e=hex.DecodeString(m["probe_digest"]);e!=nil{return out,errors.New("invalid digest")};pr,e:=probe(m["media"]);if e!=nil||pr.Digest!=m["probe_digest"]{return out,errors.New("probe digest mismatch")};sig,e:=base64.StdEncoding.DecodeString(m["signature"]);if e!=nil||len(sig)!=ed25519.SignatureSize{return out,errors.New("invalid signature")};msg:=strings.Join([]string{"relaycast-edge-v1",xe.ID,xe.Source,xe.Target,m["media"],m["probe_digest"]},"\x00");if !ed25519.Verify(pub,[]byte(msg),sig){return out,errors.New("signature verification failed")};edges=append(edges,reportEdge{xe.ID,xe.Source,xe.Target,m["media"],m["probe_digest"],m["signature"]})};slices.SortFunc(edges,func(a,b reportEdge)int{return strings.Compare(a.ID,b.ID)});level:=[][]byte{};for _,edge:=range edges{b,_:=json.Marshal(edge);h:=sha256.Sum256(append([]byte("relaycast-leaf-v1\x00"),b...));level=append(level,h[:])};for len(level)>1{next:=[][]byte{};for i:=0;i<len(level);i+=2{r:=level[i];if i+1<len(level){r=level[i+1]};b:=append([]byte("relaycast-node-v1\x00"),level[i]...);b=append(b,r...);h:=sha256.Sum256(b);next=append(next,h[:])};level=next};return report{"relaycast.provenance/v1",g.ID,gd["public_key"],edges,hex.EncodeToString(level[0])},nil}
func strict(c *gin.Context,v any)error{d:=json.NewDecoder(io.LimitReader(c.Request.Body,maxInput+1));d.DisallowUnknownFields();if e:=d.Decode(v);e!=nil{return e};if d.Decode(&struct{}{})!=io.EOF{return errors.New("trailing JSON")};return nil}
func fail(c *gin.Context,status int,code,msg string){c.JSON(status,gin.H{"error":gin.H{"code":code,"message":msg}})}
func router()*gin.Engine{gin.SetMode(gin.ReleaseMode);r:=gin.New();r.Use(gin.Recovery());r.POST("/v1/probe",func(c *gin.Context){var q struct{Media string `json:"media"`};if strict(c,&q)!=nil{fail(c,400,"bad_request","invalid request");return};p,e:=probe(q.Media);if e!=nil{fail(c,422,"invalid_evidence",e.Error());return};c.JSON(200,p)});r.POST("/v1/attest",func(c *gin.Context){var q struct{GraphML string `json:"graphml"`};if strict(c,&q)!=nil||q.GraphML==""{fail(c,400,"bad_request","invalid request");return};p,e:=attest(q.GraphML);if e!=nil{fail(c,422,"invalid_evidence",e.Error());return};c.JSON(200,p)});return r}
func main(){if len(os.Args)>1&&os.Args[1]=="reproduce"{fs:=os.Args[2:];graph,out:="","";for len(fs)>=2{switch fs[0]{case "--graph":graph=fs[1];case "--out":out=fs[1];default:fmt.Fprintln(os.Stderr,"invalid arguments");os.Exit(2)};fs=fs[2:]};if graph==""||out==""||len(fs)!=0{os.Exit(2)};r,e:=attest(graph);if e!=nil{fmt.Fprintln(os.Stderr,"invalid evidence");os.Exit(1)};b,_:=json.Marshal(r);b=append(b,'\n');if e=os.MkdirAll(filepath.Dir(out),0755);e==nil{tmp:=out+".tmp";e=os.WriteFile(tmp,b,0644);if e==nil{e=os.Rename(tmp,out)}};if e!=nil{fmt.Fprintln(os.Stderr,"write failed");os.Exit(1)};return};addr:=os.Getenv("LISTEN_ADDR");if addr==""{addr=":8080"};if e:=router().Run(addr);e!=nil{panic(e)}}
